version: '3.8'
services:
  ecommerce_store:
    container_name: 'ecommerce_store'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3245:8080'
    volumes:
      - '/home/istad/kak-bank/images:/images'
networks:
  default:
    external: true
    name: ecommerce_store-net
